version: "3.1"
services:
  playground:
    build: .
    env_file:
      - .env
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - dockerDB
  dockerDB:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
